### ISSUE TITLE
第4章の動作確認について質問

### ISSUE THREAD

**Issue by mira-q** [nabettu/mymarkdown#9]
教えていただけませんか😣
第4章のソースについて、デプロイしたアプリだとuserデータが取得できるのですが、`npm run dev`したアプリだと取得できません。`console.log(user);`の部分がundefinedになってしまいます。
毎回デプロイして動作確認するのは大変だと思うのですが、これはこういうものなのでしょうか。

**Comment by nabettu** [comment]
issueありがとうございます！

デプロイせずとも、ローカルでも確認できるはずです！（Firebaseの管理画面でのAuthentifation→許可ドメインでlocalhostがデフォルトで許可になっているため。）
そのため ```firebase-auth.js``` の読み込みが抜けているかどうかなどをチェックして頂いてもよろしいでしょうか？
わからなければソースを見せていただければレビューいたします！

**Comment by mira-q** [comment]
Twitterでサポートありがとうございました。
MacでGoogle Chrome.appを削除、更に`~/Library/Application Support/Google/Chrome`内を全て削除し、再インストールしたら、ローカルでも確認できるようになりました！
